---
title: "Untitled"
author: "Karel"
date: "2023-01-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
path = '/Users/karel/Documents/GitHub/MIRT-VAE-QMAtrix/data/missing/'

a_true = read.csv(paste0(path, 'a.csv'), row.names = 1)
d_true = read.csv(paste0(path, 'd.csv'), row.names = 1)
theta_true = read.csv(paste0(path, 'theta.csv'), row.names = 1)
data = read.csv(paste0(path, 'data.csv'), row.names = 1)

```

```{r}
library(mirt)

print('initializing pars...')
pars <- mirt(data1,ndim, pars = 'values', technical = list())

# set some loadings to zero
if(ndim==1){
  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1), ]$value = 0
  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1), ]$est = FALSE
} else if (ndim==2){
  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1:5), ]$value = 0
  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1:5), ]$est = FALSE
  pars[pars$name == 'a2' & pars$item %in% paste0('Item_', 6:10), ]$value = 0
  pars[pars$name == 'a2' & pars$item %in% paste0('Item_', 6:10), ]$est = FALSE
}else if (ndim==3){
  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1:10), ]$value = 0
  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1:10), ]$est = FALSE
  pars[pars$name == 'a2' & pars$item %in% paste0('Item_', 11:20), ]$value = 0
  pars[pars$name == 'a2' & pars$item %in% paste0('Item_', 11:20), ]$est = FALSE
  pars[pars$name == 'a3' & pars$item %in% paste0('Item_', 21:30), ]$value = 0
  pars[pars$name == 'a3' & pars$item %in% paste0('Item_', 21:30), ]$est = FALSE
}

```

