---
title: "Untitled"
author: "Karel"
date: "2023-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mirt)
ndim=3
sparsity=0
theta1 <- matrix(rnorm(1000*ndim), ncol=ndim)
d1 <- matrix(runif(28, -2, 2))
a1 <- matrix(runif(28*ndim,.5,2), ncol=ndim)
Q = read.csv('~/Documents/GitHub/MIRT-VAE-QMAtrix/data/dylan/QMatrix.csv', header=F)


print('simulating data...')
data1 = simdata(a1, d1, itemtype = '2PL', Theta = theta1)
data1[sample(length(data1), length(data1)*sparsity, replace = FALSE)] <- NA

#write.csv(data1, file='~/Documents/GitHub/MIRT-VAE-QMAtrix/data/missing10large/data.csv')
#write.csv(a1, file='~/Documents/GitHub/MIRT-VAE-QMAtrix/data/missing10large/a.csv')
#write.csv(d1, file='~/Documents/GitHub/MIRT-VAE-QMAtrix/data/missing10large/d.csv')
#write.csv(theta1, file='~/Documents/GitHub/MIRT-VAE-QMAtrix/data/missing10large/theta.csv')


#data1 = read.csv('~/Documents/GitHub/MIRT-VAE-QMAtrix/tmp.csv', header = F)
#colnames(data1) = paste0('Item_', 1:400)
#a1 = read.csv('~/Documents/GitHub/MIRT-VAE-QMAtrix/atmp.csv', header = F)
#d1 = read.csv('~/Documents/GitHub/MIRT-VAE-QMAtrix/btmp.csv', header = F)
#theta1 = read.csv('~/Documents/GitHub/MIRT-VAE-QMAtrix/thetatmp.csv', header = F)


# initialize paramters
print('initializing pars...')
pars <- mirt(data1,ndim, pars = 'values', technical = list())

# set some loadings to zero
#if(ndim==1){
#  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1), ]$value = 0
#  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1), ]$est = FALSE
#} else if (ndim==2){
#  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1:5), ]$value = 0
#  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1:5), ]$est = FALSE
#  pars[pars$name == 'a2' & pars$item %in% paste0('Item_', 6:10), ]$value = 0
#  pars[pars$name == 'a2' & pars$item %in% paste0('Item_', 6:10), ]$est = FALSE
#}else if (ndim==3){
#  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1:10), ]$value = 0
#  pars[pars$name == 'a1' & pars$item %in% paste0('Item_', 1:10), ]$est = FALSE
#  pars[pars$name == 'a2' & pars$item %in% paste0('Item_', 11:20), ]$value = 0
#  pars[pars$name == 'a2' & pars$item %in% paste0('Item_', 11:20), ]$est = FALSE
#  pars[pars$name == 'a3' & pars$item %in% paste0('Item_', 21:30), ]$value = 0
#  pars[pars$name == 'a3' & pars$item %in% paste0('Item_', 21:30), ]$est = FALSE
#}

# set values to zero using Qmatrix

for (dim in 1:3){
  for (item in 1:28){
    if (Q[item, dim] == 0){
      pars[pars$name == paste0('a', dim) & pars$item == paste0('Item_', item), ]$value = 0
      pars[pars$name == paste0('a', dim) & pars$item == paste0('Item_', item), ]$est = FALSE
    }
  }
}


fit =mirt(data1, 
     ndim, 
     method = 'EM', 
     randompars = F,
     pars = pars,
     lambda=c(1,0)
    )
#save(fit, file='~/Documents/GitHub/MIRT-VAE-QMAtrix/fitfull.RData')
#write.csv(data1, '~/Documents/GitHub/MIRT-VAE-QMAtrix/datafull.csv')

itempars <- coef(fit, simplify = TRUE)$items
a <- itempars[,1:(ncol(itempars)-3)]
d <- itempars[, ncol(itempars)-2]
theta <- fscores(fit)

for (i in 1:3){
  if (cor(a[,i], a1[,i])<0){
    a[,i] = a[,i] * -1 
    theta[,i] = theta[,i] * -1 
  }
}


mse <- function(a,b){
  mean((a-b)^2)
}
theta[is.na(theta)]=0
for (i in 1:3){
  plot(a1[,i], a[,i], main= paste('Dimension ', i, 'MSE: ', round(mse(a1[,i], a[,i]),4)))
  lines(a[,i], a[,i])
  plot(theta1[,i], theta[,i], main= paste('Dimension ', i, 'MSE: ', round(mse(theta1[,i], theta[,i]),4)))
}

plot(d1[,1], d, main= paste('Dimension ', i, 'MSE: ', round(mse(d, d1[,1]),4)))

mse(as.matrix(a1), as.matrix(a))
mse(as.matrix(d1), as.matrix(d))
mse(as.matrix(theta1), as.matrix(theta))
# .17, .97, .71
mean(is.na(data1))

```

